# Generated by Django 4.2.16 on 2024-09-28 01:33

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.utils.get_unique_file_path, validators=[core.utils.validate_file_extension])),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('government_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_due_date', models.DateField()),
                ('debt_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PE'), ('INVOICE CREATED', 'IC'), ('NOTIFICATION SENT', 'NS')], default='PENDING', max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.file')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
    ]
